import React, { useState, useCallback, useEffect } from 'react';
import useWebSocket, { ReadyState } from 'react-use-websocket';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home = () => {
  //Public API that will echo messages sent to it back to the client
  const socketUrl = 'ws://localhost:8080';
  const [messageHistory, setMessageHistory] = useState([]);
  const { sendMessage, lastMessage, readyState } = useWebSocket(socketUrl);
  useEffect(() => {
    if (lastMessage !== null) {
      console.log(lastMessage.data);
    }
    if (lastMessage !== null) {
      setMessageHistory((prev) => prev.concat(lastMessage));
    }
  }, [lastMessage, setMessageHistory]);

  useEffect(()=>{
    // HOW TO SEND MSG.
    setInterval(() => {
      const message = {
        n: 'CommandExchange',
        d: {
          t: 'backend',
          m: {
            main: 'this message is sent from NEXTJS INTERFACE',
            time: +new Date()
          },
          ts: 11,
        },
      };
      sendMessage(JSON.stringify(message))
      console.log("I sent the message ")
    }, 3000);
    
  },[])

  const connectionStatus = {
    [ReadyState.CONNECTING]: 'Connecting',
    [ReadyState.OPEN]: 'Open',
    [ReadyState.CLOSING]: 'Closing',
    [ReadyState.CLOSED]: 'Closed',
    [ReadyState.UNINSTANTIATED]: 'Uninstantiated',
  }[readyState];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <p>Hello World!</p>
          <span>The WebSocket is currently {connectionStatus}</span>
          {lastMessage && <p>{lastMessage.data}</p>}
        </div>
      </main>
    </div>
  );
};

export default Home;
